export const chats = [
  {
    avatar: "",
    name: "John Doe",
    _id: "1",
    groupChat: false,
    sameSender: false,
    isOnline: true,
    newMessageAlert: { count: 1 },
    members: ["1", "2"],
  },
  {
    avatar: "",
    name: "Jane Doe",
    _id: "2",
    groupChat: false,
    sameSender: false,
    isOnline: false,
    newMessageAlert: { count: 0 },
    members: ["1", "2"],
  },
  {
    avatar: "",
    name: "John Doe",
    _id: "3",
    groupChat: false,
    sameSender: false,
    isOnline: false,
    newMessageAlert: { count: 0 },
    members: ["1", "2", "3"],
  },
  {
    avatar: "",
    name: "Group Alpha",
    _id: "4",
    groupChat: true,
    sameSender: false,
    isOnline: false,
    newMessageAlert: { count: 2 },
    members: ["1", "2", "3", "4"],
  },
  {
    avatar: "",
    name: "John Doe",
    _id: "5",
    groupChat: false,
    sameSender: false,
    isOnline: false,
    newMessageAlert: { count: 0 },
    members: ["5", "6", "7", "8"],
  },
  {
    avatar: "",
    name: "Group Beta",
    _id: "6",
    groupChat: true,
    sameSender: true,
    isOnline: true,
    newMessageAlert: { count: 3 },
    members: ["2", "3", "6"],
  },
  {
    avatar: "",
    name: "Chris Wilson",
    _id: "7",
    groupChat: false,
    sameSender: false,
    isOnline: true,
    newMessageAlert: { count: 1 },
    members: ["7", "8"],
  },
  {
    avatar: "",
    name: "Group Gamma",
    _id: "8",
    groupChat: true,
    sameSender: false,
    isOnline: false,
    newMessageAlert: { count: 5 },
    members: ["4", "5", "8"],
  },
  {
    avatar: "",
    name: "Jessica Taylor",
    _id: "9",
    groupChat: false,
    sameSender: true,
    isOnline: true,
    newMessageAlert: { count: 0 },
    members: ["9"],
  },
  {
    avatar: "",
    name: "Group Delta",
    _id: "10",
    groupChat: true,
    sameSender: false,
    isOnline: false,
    newMessageAlert: { count: 4 },
    members: ["10", "11", "12"],
  },
  {
    avatar: "",
    name: "Michael Brown",
    _id: "11",
    groupChat: false,
    sameSender: false,
    isOnline: false,
    newMessageAlert: { count: 2 },
    members: ["11", "12"],
  },
  {
    avatar: "",
    name: "Group Epsilon",
    _id: "12",
    groupChat: true,
    sameSender: true,
    isOnline: false,
    newMessageAlert: { count: 1 },
    members: ["1", "12", "13"],
  },
  {
    avatar: "",
    name: "Rebecca Lewis",
    _id: "13",
    groupChat: false,
    sameSender: false,
    isOnline: true,
    newMessageAlert: { count: 0 },
    members: ["13", "14"],
  },
  {
    avatar: "",
    name: "Group Zeta",
    _id: "14",
    groupChat: true,
    sameSender: true,
    isOnline: true,
    newMessageAlert: { count: 7 },
    members: ["15", "16", "17", "18"],
  },
  {
    avatar: "",
    name: "Anna Thompson",
    _id: "15",
    groupChat: false,
    sameSender: false,
    isOnline: false,
    newMessageAlert: { count: 3 },
    members: ["19"],
  },
];

export const sampleUsers = [
  {
    name: "John Doe",
    _id: "1",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  {
    name: "Jane Doe",
    _id: "2",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  { name: "Jane Doe", _id: "3", avatar: ["https://randomuser.me/api"] },
  {
    name: "Jane Doe",
    _id: "4",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  { name: "John Smith", _id: "5", avatar: ["https://randomuser.me/api"] },
  {
    name: "Emily Johnson",
    _id: "6",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  { name: "Michael Brown", _id: "7", avatar: ["https://randomuser.me/api"] },
  {
    name: "Sarah Davis",
    _id: "8",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  { name: "Chris Wilson", _id: "9", avatar: ["https://randomuser.me/api"] },
  {
    name: "Anna Thompson",
    _id: "10",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  { name: "James White", _id: "11", avatar: ["https://randomuser.me/api"] },
  {
    name: "Jessica Taylor",
    _id: "12",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  { name: "David Moore", _id: "13", avatar: ["https://randomuser.me/api"] },
  {
    name: "Susan Clark",
    _id: "14",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  { name: "Kevin Harris", _id: "15", avatar: ["https://randomuser.me/api"] },
  {
    name: "Rebecca Lewis",
    _id: "16",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  { name: "Brian Walker", _id: "17", avatar: ["https://randomuser.me/api"] },
  {
    name: "Natalie Young",
    _id: "18",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  { name: "Andrew Hall", _id: "19", avatar: ["https://randomuser.me/api"] },
  {
    name: "Laura Allen",
    _id: "20",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  { name: "Robert King", _id: "21", avatar: ["https://randomuser.me/api"] },
  {
    name: "Rachel Scott",
    _id: "22",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  { name: "Patrick Adams", _id: "23", avatar: ["https://randomuser.me/api"] },
  {
    name: "Monica Baker",
    _id: "24",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  { name: "Samuel Wright", _id: "25", avatar: ["https://randomuser.me/api"] },
  {
    name: "Isabella Green",
    _id: "26",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  { name: "Henry Hill", _id: "27", avatar: ["https://randomuser.me/api"] },
  {
    name: "Olivia Edwards",
    _id: "28",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
  { name: "Joshua Mitchell", _id: "29", avatar: ["https://randomuser.me/api"] },
  {
    name: "Emma Carter",
    _id: "30",
    avatar: ["https://randomuser.me/api", "https://randomuser.me/api"],
  },
];

export const sampleNotifications = [
  {
    sender: {
      name: "John Doe",
      avatar: "https://randomuser.me/api",
    },
    _id: "1",
  },
  {
    sender: {
      name: "Jane Doe",
      avatar: "https://randomuser.me/api",
    },
    _id: "2",
  },
];

export const sampleMessage = [
  {
    attachments: [
      {
        public_id: "1",
        url: "https://randomuser.me/api",
      },
    ],
    content: "Hello World",
    _id: "1",
    sender: {
      name: "John Doe",
      _id: "2",
    },
    chat: "chatId",
    createdAt: "2021-09-20T00:00:00.000Z",
  },
  {
    attachments: [
      {
        public_id: "1",
        url: "https://dummyimage.com/300.png",
      },
    ],
    content: "Hello World",
    _id: "2",
    sender: {
      name: "Jabe Doe",
      _id: "1",
    },
    chat: "avrwvawv",
    createdAt: "2021-09-20T00:00:00.000Z",
  },
];
